[font]
size = 12.0
[font.offset]
x = 0
y = 0
[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
[font.bold]
family = "JetBrainsMono NF"
style = "Bold"
[font.italic]
family = "JetBrainsMono NF"
style = "Italic"
[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"
