[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "k"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "j"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "d"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "u"
mods = "Control|Shift"
